spring:
  profiles:
   actives:
     - dev
---

server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml  #mybatis所在路径
  type-aliases-package: com.xy.springcloud.entity #entity别名类
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml #mapper映射文件

spring:
  profiles: dev
  application:
    name: mycloud-config-provider-8001  #集群中 这个名字需要统一定义
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@172.16.1.96:1521:mvdev
    username: iconn
    password: iconn
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

eureka:
  client:    #客户端注册进eureka的服务列表中
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/ #将服务注册到eureka 集群的地址
    instance:
      instance-id: myclouddeptprovider8001 #修改eureka的状态名称
      prefer-ip-address: true     #访问路径可以显示IP地址

#eureka注册的服务的详细超链接信息
info:
  app.name: myCloud
  company.name: ariix
  build.artifactId: ${artifactId}
  build.version: ${project.version}
     
    
